package common

const (
	MATCH_CREATION         = "MATCH_CREATION"
	MATCH_HOST_ASSIGNMENT  = "MATCH_HOST_ASSIGNMENT"
	MATCH_USER_JOIN        = "MATCH_USER_JOIN"
	MATCH_USER_LEFT        = "MATCH_USER_LEFT"
	MATCH_DISBAND          = "MATCH_DISBAND"
	MATCH_GAME_PLAYTHROUGH = "MATCH_GAME_PLAYTHROUGH"
)
